GET http://localhost:2485/member

###

GET http://localhost:2485/member/Elon

###

POST http://localhost:2485/member
Content-Type: application/json

{
  "username": "Jaohaan",
  "password": "password"
}

###

PATCH http://localhost:2485/member/James
Content-Type: application/json

{
  "username": "Omar",
  "password": "password1"
}

###

DELETE http://localhost:2485/member/James

###

DELETE http://localhost:2485/member

###

# BLog Routes

GET http://localhost:2485/blog

###

GET http://localhost:2485/blog/LoQuea

### 

POST http://localhost:2485/blog
Content-Type: application/json

{
  "title": "BookasdaaTiatle",
  "author": "Author",
  "content": "Hello"
}

###

DELETE http://localhost:2485/blog