GET http://localhost:2485/member

###

GET http://localhost:2485/member/Elon

###

POST http://localhost:2485/member
Content-Type: application/json

{
  "username": "John",
  "password": "password"
}

###

PATCH http://localhost:2485/member/James
Content-Type: application/json

{
  "username": "Omar",
  "password": "password1"
}

###

DELETE http://localhost:2485/member/James

###

DELETE http://localhost:2485/member